import Head from "next/head";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Commitment from "@/components/Commitment";
import Books from "@/components/Books";
import FeaturedBooks from "@/components/FeaturedBooks";
import BookReviews from "@/components/BookReviews";
import Banner from "@/components/Banner";
import ScrollReveal from "@/components/ScrollReveal";

export default function Home() {
  return (
    <>
      <Head>
        <title>El Ran Fortune | Standard & Elegance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className="bg-background overflow-hidden">
        <ScrollReveal>
          <Hero />
        </ScrollReveal>
        
        <ScrollReveal>
          <About />
        </ScrollReveal>
        
        <ScrollReveal>
          <Commitment />
        </ScrollReveal>

        {/* <ScrollReveal>
          <Books />
        </ScrollReveal> */}
        
        <ScrollReveal>
          <FeaturedBooks />
        </ScrollReveal>
        
        <ScrollReveal>
          <BookReviews />
        </ScrollReveal>

        <ScrollReveal overflow="visible">
          <Banner />
        </ScrollReveal>
      </div>
    </>
  );
}
